spring:
  application:
    name: com.saymk.cloudstorage
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: false
          use_query_cache: false
        hbm2ddl:
          auto: none
        generate_statistics: true

    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shestoy
    username: admin
    password: admin